### ISSUE TITLE
Target setting should be outside the RARED method

### ISSUE THREAD

**Issue by mohittahiliani** [ShikhaBakshi/Implementation-of-RARED-in-Linux-Kernel#6]
Target setting is currently done inside the RARED method, which is not correct.

Configuration of target settings should be "one time" computation. By keeping it inside the RARED method, you are increase the computation largely because whenever RARED is called - target setting would be configured again.

Follow the target setting done for ARED, and do it same way.

**Comment by mohittahiliani** [comment]
This is what the new commit has:

/* RED Adaptative target :
 * [min_th + 0.4*(min_th - max_th),
 *  min_th + 0.6*(min_th - max_th)].
 */

1. Spelling of Adaptive is wrong.
2. It should be Refined Adaptive RED and not RED Adaptive
3. 0.4 should be 0.48
4. 0.6 should be 0.52

**Comment by kajoljain379** [comment]
Hello Sir,
 actually in linux kernel code,everywhere they use adaptative rather then adaptive. Even in functions in other files present in net folder they have used adaptative,thats why we use this name and
/* RED Adaptative target :

[min_th + 0.4*(min_th - max_th),
min_th + 0.6*(min_th - max_th)].
*/ 
this part is in actual linux code.
we create new function for changing parameters that is, rared_red_set_params and calling it in red_change function.

So, should we change the parameter in the existing function or keep the new function because if we change in the existing function, the parameters for Adaptive RED will be change.

**Comment by mohittahiliani** [comment]
@kajoljain379 - do not close the issue until it is "completely" addressed.

Apart from the spelling, there are other 3 changes that have been suggested.

Until those changes are not committed in the repo, please do not close the issue.

It becomes difficult to keep track which changes have been incorporated and which are pending.

**Comment by kajoljain379** [comment]
Sorry sir, We will keep this in mind for next time. And sir other issues of changing target value have been done  in new function "rared_red_set_params"which is defined below the red_set_parms function.

/* Refined Adaptative RED target :
	 * [min_th + 0.48*(min_th - max_th),
	 *  min_th + 0.52*(min_th - max_th)].
	 */
	delta /= 25;

	p->target_min = qth_min + 12*delta;
	p->target_max = qth_min + 13*delta;

**Comment by mohittahiliani** [comment]
Noted.
